!/**
 * Highcharts JS v12.6.0 (2026-04-13)
 * @module highcharts/themes/sand-signika
 * @requires highcharts
 *
 * (c) 2009-2026 Highsoft AS
 * Author: Torstein Hønsi
 *
 * A commercial license may be required depending on use.
 * See www.highcharts.com/license
 */function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(e._Highcharts):"function"==typeof define&&define.amd?define("highcharts/themes/sand-signika",["highcharts/highcharts"],function(e){return t(e)}):"object"==typeof exports?exports["highcharts/themes/sand-signika"]=t(e._Highcharts):e.Highcharts=t(e.Highcharts)}("u"<typeof window?this:window,function(e){return function(){"use strict";var t,o,r={944:function(t){t.exports=e}},n={};function i(e){var t=n[e];if(void 0!==t)return t.exports;var o=n[e]={exports:{}};return r[e](o,o.exports,i),o.exports}i.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return i.d(t,{a:t}),t},i.d=function(e,t){for(var o in t)i.o(t,o)&&!i.o(e,o)&&Object.defineProperty(e,o,{enumerable:!0,get:t[o]})},i.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)};var s={};i.d(s,{default:function(){return u}});var a=i(944),c=i.n(a),l=c().doc;c().win;function p(e,t){var o;for(o in e||(e={}),t)e[o]=t[o];return e}Array.prototype.find;var f=c().setOptions;(t=o||(o={})).options={colors:["#f45b5b","#8085e9","#8d4654","#7798BF","#aaeeee","#ff0066","#eeaaee","#55BF3B","#DF5353","#7798BF","#aaeeee"],chart:{backgroundColor:null,style:{fontFamily:"Signika, serif"}},title:{style:{color:"black",fontSize:"16px",fontWeight:"bold"}},subtitle:{style:{color:"black"}},tooltip:{borderWidth:0},legend:{backgroundColor:"#E0E0E8",itemStyle:{fontWeight:"bold",fontSize:"13px"}},xAxis:{labels:{style:{color:"#6e6e70"}}},yAxis:{labels:{style:{color:"#6e6e70"}}},plotOptions:{series:{shadow:!0},candlestick:{lineColor:"#404048"},map:{shadow:!1}},navigator:{xAxis:{gridLineColor:"#D0D0D8"}},rangeSelector:{buttonTheme:{fill:"white",stroke:"#C0C0C8","stroke-width":1,states:{select:{fill:"#D0D0D8"}}}},scrollbar:{trackBorderColor:"#C0C0C8"}},t.apply=function(){var e,o,r,n,i,s,a,h,u,d,g;e={href:"https://fonts.googleapis.com/css?family=Signika:400,700",rel:"stylesheet",type:"text/css"},o=document.getElementsByTagName("head")[0],r=l.createElement("link"),e&&p(r,e),o&&o.appendChild(r),n=c().Chart,i="afterGetContainer",s=function(){this.container.style.background="url(https://www.highcharts.com/samples/graphics/sand.png)"},void 0===a&&(a={}),h="function"==typeof n&&n.prototype||n,Object.hasOwnProperty.call(h,"hcEvents")||(h.hcEvents={}),u=h.hcEvents,c().Point&&n instanceof c().Point&&n.series&&n.series.chart&&(n.series.chart.runTrackerClick=!0),(d=n.addEventListener)&&d.call(n,i,s,!!c().supportsPassiveEvents&&{passive:void 0===a.passive?-1!==i.indexOf("touch"):a.passive,capture:!1}),u[i]||(u[i]=[]),g={fn:s,order:"number"==typeof a.order?a.order:1/0},u[i].push(g),u[i].sort(function(e,t){return e.order-t.order}),f(t.options)};var h=o;c().theme=h.options,h.apply();var u=c();return s.default}()});